config/routes.rb
Rails.application.routes.draw do
  # resources :usuarios
  resources :proveedores
  resources :empleados
  resources :herramienta_maquinaria
  resources :obras_proyectos
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :users
  resources :users, only:[:index, :show]
  root to: "home#index"
  
end

app/models/proveedore.rb
class Proveedore < ApplicationRecord
end

app/controllers/proveedores_controller.rb
class ProveedoresController < ApplicationController

  before_action :authenticate_user!

  before_action :set_proveedore, only: %i[ show edit update destroy ]

  # GET /proveedores or /proveedores.json
  def index
    @proveedores = Proveedore.all
  end

  # GET /proveedores/1 or /proveedores/1.json
  def show
  end

  # GET /proveedores/new
  def new
    @proveedore = Proveedore.new
  end

  # GET /proveedores/1/edit
  def edit
  end

  # POST /proveedores or /proveedores.json
  def create
    @proveedore = Proveedore.new(proveedore_params)

    respond_to do |format|
      if @proveedore.save
        format.html { redirect_to @proveedore, notice: "El proveedor ha sido creado con exito." }
        format.json { render :show, status: :created, location: @proveedore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proveedores/1 or /proveedores/1.json
  def update
    respond_to do |format|
      if @proveedore.update(proveedore_params)
        format.html { redirect_to @proveedore, notice: "El proveedor ha sido actualizado con exito." }
        format.json { render :show, status: :ok, location: @proveedore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedores/1 or /proveedores/1.json
  def destroy
    @proveedore.destroy
    respond_to do |format|
      format.html { redirect_to proveedores_url, notice: "El proveedor ha sido eliminado con exito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proveedore
      @proveedore = Proveedore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proveedore_params
      params.require(:proveedore).permit(:compañia, :telefono, :nombreContacto, :tipoProveedor, :fechaCreacion, :fechaActualizacion)
    end
end

app/helpers/proveedores_helper.rb
module ProveedoresHelper
end

app/views/proveedores/_form.html.erb
<%= form_with(model: proveedore) do |form| %>
  <% if proveedore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proveedore.errors.count, "error") %> prohibited this proveedore from being saved:</h2>

      <ul>
        <% proveedore.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :compañia %>
    <%= form.text_field :compañia %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono %>
  </div>

  <div class="field">
    <%= form.label :nombreContacto %>
    <%= form.text_field :nombreContacto %>
  </div>

  <div class="field">
    <%= form.label :tipoProveedor %>
    <%= form.text_field :tipoProveedor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proveedores/edit.html.erb
<h1>Editar Proveedore</h1>

<%= render 'form', proveedore: @proveedore %>

<%= link_to 'Ver', @proveedore %> |
<%= link_to 'Regresar', proveedores_path %>

app/views/proveedores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proveedores</h1>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Compañia</th>
      <th>Telefono</th>
      <th>Nombre de contacto</th>
      <th>Tipo de proveedor</th>
      <th>Fecha de creacion</th>
      <th>Fecha de actualizacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proveedores.each do |proveedore| %>
      <tr>
        <td><%= proveedore.id %></td>
        <td><%= proveedore.compañia %></td>
        <td><%= proveedore.telefono %></td>
        <td><%= proveedore.nombreContacto %></td>
        <td><%= proveedore.tipoProveedor %></td>
        <td><%= proveedore.created_at %></td>
        <td><%= proveedore.updated_at %></td>
        <td><%= link_to 'Ver', proveedore %></td>
        <td><%= link_to 'Editar', edit_proveedore_path(proveedore) %></td>
        <td><%= link_to 'Eliminar', proveedore, method: :delete, data: { confirm: 'Esta seguro de eliminar' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo proveedor', new_proveedore_path %>

app/views/proveedores/new.html.erb
<h1>Nuevo Proveedor</h1>

<%= render 'form', proveedore: @proveedore %>

<%= link_to 'Regresar', proveedores_path %>

app/views/proveedores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @proveedore.id%>
</p>

<p>
  <strong>Compañia:</strong>
  <%= @proveedore.compañia %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @proveedore.telefono %>
</p>

<p>
  <strong>Nombrecontacto:</strong>
  <%= @proveedore.nombreContacto %>
</p>

<p>
  <strong>Tipoproveedor:</strong>
  <%= @proveedore.tipoProveedor %>
</p>

<p>
  <strong>Fechacreacion:</strong>
  <%= @proveedore.created_at %>
</p>

<p>
  <strong>Fechaactualizacion:</strong>
  <%= @proveedore.updated_at %>
</p>

<%= link_to 'Editar', edit_proveedore_path(@proveedore) %> |
<%= link_to 'Regresar', proveedores_path %>