config/routes.rb
Rails.application.routes.draw do
  # resources :usuarios
  resources :proveedores
  resources :empleados
  resources :herramienta_maquinaria
  resources :obras_proyectos
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :users
  resources :users, only:[:index, :show]
  root to: "home#index"
  
end

app/models/empleado.rb
class Empleado < ApplicationRecord
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController

  before_action :authenticate_user!

  before_action :set_empleado, only: [ :show, :edit, :update, :destroy ]

  # GET /empleados or /empleados.json
  def index
    @empleados = Empleado.all
  end

  # GET /empleados/1 or /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados or /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)

    respond_to do |format|
      if @empleado.save
        format.html { redirect_to @empleado, notice: "Empleado ha sido creado con exito." }
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1 or /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to @empleado, notice: "Empleado ha sido actualizado con exito." }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1 or /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: "Empleado ha sido eliminado con exito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def empleado_params
      params.require(:empleado).permit(:nombre, :apellidoPaterno, :apellidoMaterno, :fechaNacimiento, :telefono, :email, :nss, :categoria, :activo, :fechaCreacion, :fehcaActualizacion)
    end
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/_form.html.erb
<%= form_with(model: empleado) do |form| %>
  <% if empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
        <% empleado.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellidoPaterno %>
    <%= form.text_field :apellidoPaterno %>
  </div>

  <div class="field">
    <%= form.label :apellidoMaterno %>
    <%= form.text_field :apellidoMaterno %>
  </div>

  <div class="field">
    <%= form.label :fechaNacimiento %>
    <%= form.date_select :fechaNacimiento %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :nss %>
    <%= form.text_field :nss %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.text_field :categoria %>
  </div>

  <div class="field">
    <%= form.label :activo %>
    <%= form.text_field :activo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<h1>Editar Empleado</h1>

<%= render 'form', empleado: @empleado %>

<%= link_to 'Ver', @empleado %> |
<%= link_to 'Regresar', empleados_path %>

app/views/empleados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empleados</h1>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Apellido paterno</th>
        <th>Apellido materno</th>
        <th>Fecha de nacimiento</th>
        <th>Telefono</th>
        <th>Email</th>
        <th>Nss</th>
        <th>Categoria</th>
        <th>Activo</th>
        <th>Fecha de creacion</th>
        <th>Fecha de actualizacion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @empleados.each do |empleado| %>
        <tr>
          <td><%= empleado.id %></td>
          <td><%= empleado.nombre %></td>
          <td><%= empleado.apellidoPaterno %></td>
          <td><%= empleado.apellidoMaterno %></td>
          <td><%= empleado.fechaNacimiento %></td>
          <td><%= empleado.telefono %></td>
          <td><%= empleado.email %></td>
          <td><%= empleado.nss %></td>
          <td><%= empleado.categoria %></td>
          <td><%= empleado.activo %></td>
          <td><%= empleado.created_at %></td>
          <td><%= empleado.updated_at %></td>
          <td><%= link_to 'Ver', empleado %></td>
          <td><%= link_to 'Editar', edit_empleado_path(empleado) %></td>
          <td><%= link_to 'Eliminar', empleado, method: :delete, data: { confirm: 'Esta seguro de eliminar?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Nuevo Empleado', new_empleado_path %>

app/views/empleados/new.html.erb
<h1>Nuevo Empleado</h1>

<%= render 'form', empleado: @empleado %>

<%= link_to 'Regresar', empleados_path %>

app/views/empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @empleado.id%>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @empleado.nombre %>
</p>

<p>
  <strong>Apellidopaterno:</strong>
  <%= @empleado.apellidoPaterno %>
</p>

<p>
  <strong>Apellidomaterno:</strong>
  <%= @empleado.apellidoMaterno %>
</p>

<p>
  <strong>Fechanacimiento:</strong>
  <%= @empleado.fechaNacimiento %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @empleado.telefono %>
</p>

<p>
  <strong>Email:</strong>
  <%= @empleado.email %>
</p>

<p>
  <strong>Nss:</strong>
  <%= @empleado.nss %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @empleado.categoria %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @empleado.activo %>
</p>

<p>
  <strong>Fechacreacion:</strong>
  <%= @empleado.created_at %>
</p>

<p>
  <strong>Fehcaactualizacion:</strong>
  <%= @empleado.updated_at %>
</p>

<%= link_to 'Editar', edit_empleado_path(@empleado) %> |
<%= link_to 'Regresar', empleados_path %>