config/routes.rb
Rails.application.routes.draw do
  # resources :usuarios
  resources :proveedores
  resources :empleados
  resources :herramienta_maquinaria
  resources :obras_proyectos
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :users
  resources :users, only:[:index, :show]
  root to: "home#index"
  
end

app/models/obras_proyecto.rb
class ObrasProyecto < ApplicationRecord



end

app/controllers/obras_proyectos_controller.rb
class ObrasProyectosController < ApplicationController

  before_action :authenticate_user!

  before_action :set_obras_proyecto, only: %i[ show edit update destroy ]

  # GET /obras_proyectos or /obras_proyectos.json
  def index
    @obras_proyectos = ObrasProyecto.all
  end

  # GET /obras_proyectos/1 or /obras_proyectos/1.json
  def show
  end

  # GET /obras_proyectos/new
  def new
    @obras_proyecto = ObrasProyecto.new
  end

  # GET /obras_proyectos/1/edit
  def edit
  end

  # POST /obras_proyectos or /obras_proyectos.json
  def create
    @obras_proyecto = ObrasProyecto.new(obras_proyecto_params)

    respond_to do |format|
      if @obras_proyecto.save
        format.html { redirect_to @obras_proyecto, notice: "La obra o proyecto ha sido creado con exito." }
        format.json { render :show, status: :created, location: @obras_proyecto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @obras_proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /obras_proyectos/1 or /obras_proyectos/1.json
  def update
    respond_to do |format|
      if @obras_proyecto.update(obras_proyecto_params)
        format.html { redirect_to @obras_proyecto, notice: "La obra o proyecto ha sido actualizado con exito." }
        format.json { render :show, status: :ok, location: @obras_proyecto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @obras_proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /obras_proyectos/1 or /obras_proyectos/1.json
  def destroy
    @obras_proyecto.destroy
    respond_to do |format|
      format.html { redirect_to obras_proyectos_url, notice: "La obra o proyecto ha sido eliminado con exito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_obras_proyecto
      @obras_proyecto = ObrasProyecto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def obras_proyecto_params
      params.require(:obras_proyecto).permit(:nombre, :descripcion, :ubicacion, :TipoObra, :MontoObra, :fechaInicio, :fechaFin, :responsable, :fechaCreacion, :fechaActualizacion)
    end
end

app/helpers/obras_proyectos_helper.rb
module ObrasProyectosHelper
end

app/views/obras_proyectos/_form.html.erb
<%= form_with(model: obras_proyecto) do |form| %>
  <% if obras_proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(obras_proyecto.errors.count, "error") %> prohibited this obras_proyecto from being saved:</h2>

      <ul>
        <% obras_proyecto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :ubicacion %>
    <%= form.text_field :ubicacion %>
  </div>

  <div class="field">
    <%= form.label :Tipobra %>
    <%= form.select :TipoObra, ["civil","electrica","mecanica"] %>
  </div>

  <div class="field">
    <%= form.label :MontoObra %>
    <%= form.number_field :MontoObra %>
  </div>

  <div class="field">
    <%= form.label :fechaInicio %>
    <%= form.date_select :fechaInicio %>
  </div>

  <div class="field">
    <%= form.label :fechaFin %>
    <%= form.date_select :fechaFin %>
  </div>

  <div class="field">
    <%= form.label :responsable %>
    <%= form.text_field :responsable %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/obras_proyectos/edit.html.erb
<h1>Editar Obras o Proyectos</h1>

<%= render 'form', obras_proyecto: @obras_proyecto %>

<%= link_to 'Ver', @obras_proyecto %> |
<%= link_to 'Regresar', obras_proyectos_path %>

app/views/obras_proyectos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Obras/Proyectos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Ubicacion</th>
      <th>Tipo de obra</th>
      <th>Monto de obra</th>
      <th>Fecha de inicio</th>
      <th>Fecha de fin</th>
      <th>Responsable</th>
      <th>Fecha de creacion</th>
      <th>Fecha de actualizacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @obras_proyectos.each do |obras_proyecto| %>
      <tr>
        <td><%= obras_proyecto.nombre %></td>
        <td><%= obras_proyecto.descripcion %></td>
        <td><%= obras_proyecto.ubicacion %></td>
        <td><%= obras_proyecto.TipoObra %></td>
        <td><%= obras_proyecto.MontoObra %></td>
        <td><%= obras_proyecto.fechaInicio %></td>
        <td><%= obras_proyecto.fechaFin %></td>
        <td><%= obras_proyecto.responsable %></td>
        <td><%= obras_proyecto.created_at %></td>
        <td><%= obras_proyecto.updated_at %></td>
        <td><%= link_to 'Ver', obras_proyecto %></td>
        <td><%= link_to 'Editar', edit_obras_proyecto_path(obras_proyecto) %></td>
        <td><%= link_to 'Eliminar', obras_proyecto, method: :delete, data: { confirm: 'estas seguro de eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Obra o Proyecto', new_obras_proyecto_path %>

app/views/obras_proyectos/new.html.erb
<h1>Nueva Obra o Proyecto</h1>

<%= render 'form', obras_proyecto: @obras_proyecto %>

<%= link_to 'Regresar', obras_proyectos_path %>

app/views/obras_proyectos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @obras_proyecto.id%>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @obras_proyecto.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @obras_proyecto.descripcion %>
</p>

<p>
  <strong>Ubicacion:</strong>
  <%= @obras_proyecto.ubicacion %>
</p>

<p>
  <strong>Tipoobra:</strong>
  <%= @obras_proyecto.TipoObra %>
</p>

<p>
  <strong>Montoobra:</strong>
  <%= @obras_proyecto.MontoObra %>
</p>

<p>
  <strong>Fechainicio:</strong>
  <%= @obras_proyecto.fechaInicio %>
</p>

<p>
  <strong>Fechafin:</strong>
  <%= @obras_proyecto.fechaFin %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @obras_proyecto.responsable %>
</p>

<p>
  <strong>Fechacreacion:</strong>
  <%= @obras_proyecto.created_at %>
</p>

<p>
  <strong>Fechaactualizacion:</strong>
  <%= @obras_proyecto.created_at %>
</p>

<%= link_to 'Editar', edit_obras_proyecto_path(@obras_proyecto) %> |
<%= link_to 'Regresar', obras_proyectos_path %>