config/routes.rb
Rails.application.routes.draw do
  # resources :usuarios
  resources :proveedores
  resources :empleados
  resources :herramienta_maquinaria
  resources :obras_proyectos
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :users
  resources :users, only:[:index, :show]
  root to: "home#index"
  
end

app/views/layouts/_menu.html.erb
<h1> Empresa industrial </h1>
    <div style="position:absolute;bottom:590px;right:50px;margin:0;padding:5px 3px;" href="#">
        <%= link_to "Cerrar sesion", destroy_user_session_path, method: 'delete', class: "btn btn-danger" %>
    </div>
    <h3>Bienvenidos</h3>
<br> 
    <div class="m-0 row justify-content-center">
        <nav class="btn-group" role="group" aria-label="Basic example ">
            <%= link_to "Inicio", root_path, class: "btn btn-success" %>
            <%= link_to "Usuarios", users_path, class: "btn btn-success" %>
            <%= link_to "Proveedores", proveedores_path, class: "btn btn-success" %>
            <%= link_to "Empleados", empleados_path, class: "btn btn-success" %>
            <%= link_to "Obras/Proyectos", obras_proyectos_path, class: "btn btn-success" %>
            <%= link_to "Herramienta/Maquinaria", herramienta_maquinaria_path, class: "btn btn-success" %>
        </nav> 
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dahsboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel = "stylesheet" href = " https://cdn.jsdelivr.net/npm/chart.js@2.9.1/dist/Chart.min.css ">
    <script src = " https://cdn.jsdelivr.net/npm/chart.js@2.9.1/dist/Chart.min.js "> </script>
  </head>

  <body style="background-color:#00EDFF;">

     <div class="container">
     
        <% if current_user %>
          <%= render "layouts/menu" %>
        
        <% end %>
        
      
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%= yield %>
       </div>
  </body>
</html>